"""esquema inicial

Revision ID: 020925e83a0f
Revises: 
Create Date: 2026-08-15 00:25:45.544986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020925e83a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_profile',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('goal_distance', sa.String(length=8), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('reference_distance_km', sa.Float(), nullable=True),
    sa.Column('reference_time_sec', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('weekly_volume_km', sa.Float(), nullable=False),
    sa.Column('longest_run_km', sa.Float(), nullable=False),
    sa.Column('base_cadence_spm', sa.Integer(), nullable=True),
    sa.Column('injuries', sa.JSON(), nullable=False),
    sa.Column('practical_problems', sa.Text(), nullable=True),
    sa.Column('technique_experience', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('gait_findings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('coach_decision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_decision_user_id'), 'coach_decision', ['user_id'], unique=False)
    op.create_table('conversation_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_user_id'), 'conversation_memory', ['user_id'], unique=False)
    op.create_table('session_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('pace_sec_per_km', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('discrepancy_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_log_user_fecha', 'session_log', ['user_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_session_log_user_id'), 'session_log', ['user_id'], unique=False)
    op.create_table('telegram_link',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_telegram_link_user_id'), 'telegram_link', ['user_id'], unique=False)
    op.create_table('wellness_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('pain_score', sa.Integer(), nullable=False),
    sa.Column('pain_area', sa.String(length=64), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wellness_log_user_fecha', 'wellness_log', ['user_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_wellness_log_user_id'), 'wellness_log', ['user_id'], unique=False)
    op.create_table('training_state',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['athlete_profile.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_state')
    op.drop_index(op.f('ix_wellness_log_user_id'), table_name='wellness_log')
    op.drop_index('ix_wellness_log_user_fecha', table_name='wellness_log')
    op.drop_table('wellness_log')
    op.drop_index(op.f('ix_telegram_link_user_id'), table_name='telegram_link')
    op.drop_table('telegram_link')
    op.drop_index(op.f('ix_session_log_user_id'), table_name='session_log')
    op.drop_index('ix_session_log_user_fecha', table_name='session_log')
    op.drop_table('session_log')
    op.drop_index(op.f('ix_conversation_memory_user_id'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    op.drop_index(op.f('ix_coach_decision_user_id'), table_name='coach_decision')
    op.drop_table('coach_decision')
    op.drop_table('athlete_profile')
    # ### end Alembic commands ###
